### ISSUE TITLE
Base Uri encoding

### ISSUE THREAD

**Issue by Tuszy** [CJ42/LUKSO-Hardhat-template#1]
Hi Jean,

Short question. Why are you setting only the url without the bytes4 prefix (https://github.com/CJ42/LUKSO-Hardhat-template/blob/recipes/test/NFTCollection.ts) for the base uri. According to the docs we need either 0x00000000 or 0x6f357c6a depending on the Token Id Type (https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-8-IdentifiableDigitalAsset.md#lsp8tokenmetadatabaseuri). Are the docs outdated regarding this?

**Comment by CJ42** [comment]
@Tuszy the docs have changed and now use `VerifiableURI` without any bytes4 prefix.

<img width="1239" alt="image" src="https://github.com/CJ42/LUKSO-Hardhat-template/assets/31145285/a9b4137e-27c9-4b7b-84ec-83f369542846">

Closing this issue as not applicable anymore.
